/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admincine.UI;

import admincine.Funcion;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author milton
 */
public class Pantalla extends javax.swing.JFrame {

    private List<Funcion> listaFunciones = new ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pantalla.class.getName());

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AddFuncion = new javax.swing.JMenuItem();
        comprarFuncion = new javax.swing.JMenuItem();
        iniciarLabores = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("CINE");

        jMenu1.setText("Menu");

        AddFuncion.setText(" Registrar función");
        AddFuncion.addActionListener(this::AddFuncionActionPerformed);
        jMenu1.add(AddFuncion);

        comprarFuncion.setText("Comprar entrada ");
        comprarFuncion.addActionListener(this::comprarFuncionActionPerformed);
        jMenu1.add(comprarFuncion);

        iniciarLabores.setText("Iniciar labores");
        iniciarLabores.addActionListener(this::iniciarLaboresActionPerformed);
        jMenu1.add(iniciarLabores);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exit.setText("Salir");
        exit.addActionListener(this::exitActionPerformed);
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel2)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void AddFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFuncionActionPerformed
        String codigo = JOptionPane.showInputDialog(this, "Ingrese el código de la función:");

        if (codigo == null || codigo.trim().isEmpty()) {
            return;
        }

        for (Funcion funcion : listaFunciones) {
            if (funcion.getCodigo().equalsIgnoreCase(codigo)) {
                JOptionPane.showMessageDialog(this, "El código ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        String pelicula = JOptionPane.showInputDialog(this, "Ingrese el nombre de la pelicula:");
        String hora = JOptionPane.showInputDialog(this, "Ingrese la hora de inicio (ejemplo: 4:30 PM):");

        Funcion funcion = new Funcion(codigo, pelicula, hora);
        listaFunciones.add(funcion);

        JOptionPane.showMessageDialog(this, "Función registrada.");
    }//GEN-LAST:event_AddFuncionActionPerformed

    private void comprarFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarFuncionActionPerformed
        if (listaFunciones.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay funciones registradas.");
            return;
        }

        int numeroDeFunciones = listaFunciones.size();
        String[] opciones = new String[numeroDeFunciones];

        for (int i = 0; i < numeroDeFunciones; i++) {
            opciones[i] = (i + 1) + ". " + listaFunciones.get(i).getPelicula() + " |" + listaFunciones.get(i).getCodigo();
        }

        String seleccion = (String) JOptionPane.showInputDialog(
                this, "Seleccione una función:", "Comprar",
                JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

        if (seleccion != null) {
            Integer opcion = Integer.parseInt(seleccion.substring(0, seleccion.indexOf("."))) - 1;
            Funcion funcionSeleccionada = listaFunciones.get(opcion);
            gestionarVentaAsiento(funcionSeleccionada);
        }
    }//GEN-LAST:event_comprarFuncionActionPerformed

    private String asientos(Funcion funcion) {
        StringBuilder mapa = new StringBuilder();
        mapa.append("Pelicula: ").append(funcion.getPelicula())
                .append("\nHora: ").append(funcion.getHora())
                .append("\n\nPuestos:\n");

        boolean[] puestos = funcion.getPuestos();
        int columnasPorFila = 5;
        int numeroDePuestos = puestos.length;

        for (int i = 0; i < numeroDePuestos; i++) {
            String estado = puestos[i] ? "[O]" : "[D]";
            mapa.append(String.format("%2d %s\t", (i + 1), estado));

            boolean finDeFila = (i + 1) % columnasPorFila == 0;

            if (finDeFila) {
                mapa.append("\n");
            }
        }

        mapa.append("\nD = Disponible, O = Ocupado")
                .append("\n\nIngrese el número de puesto a comprar (1-20):");

        return mapa.toString();
    }

    private void compraDeAsiento(Funcion funcion, String opcion) {
        int numeroPuesto;
        try {
            numeroPuesto = Integer.parseInt(opcion);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Numero no valido.");
            return;
        }

        if (numeroPuesto < 1 || numeroPuesto > 20) {
            JOptionPane.showMessageDialog(this, "Puesto fuera de rango (1-20)");
            return;
        }

        boolean compraRealziada = funcion.comprarPuesto(numeroPuesto);
        if (compraRealziada) {
            JOptionPane.showMessageDialog(this, "Puesto " + numeroPuesto + " comprado.");
        } else {
            JOptionPane.showMessageDialog(this, "El puesto ya está ocupado.", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void iniciarLaboresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarLaboresActionPerformed
        if (listaFunciones.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay funciones registradas para proyectar.");
            return;
        }
        int numeroDeFunciones = listaFunciones.size();
        
        for (int i = 0; i < numeroDeFunciones; i++) {
            Funcion funcion = listaFunciones.get(i);
            String mensaje = "====================================\n"
                    + "       REPRODUCIENDO FUNCIÓN\n"
                    + "====================================\n"
                    + "Pelicula: " + funcion.getPelicula() + "\n"
                    + "Hora: " + funcion.getHora() + "\n"
                    + "Puestos vendidos: " + funcion.getCantidadOcupados() + "\n"
                    + "Puestos disponibles: " + funcion.getCantidadDisponibles() + "\n"
                    + "====================================";

            if (i < numeroDeFunciones - 1) {
                JOptionPane.showMessageDialog(this, mensaje + "\n\nPresione Aceptar para reproducir la siguiente función...");
            } else {
                JOptionPane.showMessageDialog(this, mensaje + "\n\nTodas las funciones han sido reproducidas. Fin del día.");
            }
        }
    }//GEN-LAST:event_iniciarLaboresActionPerformed

    private void gestionarVentaAsiento(Funcion funcion) {
        String mensaje = asientos(funcion);
        String opcion = JOptionPane.showInputDialog(this, mensaje);
        if (opcion == null) {
            return;
        }
        compraDeAsiento(funcion, opcion);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pantalla().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddFuncion;
    private javax.swing.JMenuItem comprarFuncion;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuItem iniciarLabores;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
